config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "plants#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resource :users
  resources :plants, only: [:index, :show]
  get 'cart', to: 'pages#cart', as: :cart
  resource :cart, only: [:show] do
    resources :orders, only: [:new]
  end
  post 'cart/add'
  delete 'cart/remove', to: 'cart#remove', as: :cart_remove
  patch 'cart/increment_quantity/:id', to: 'cart#increment_quantity', as: :increment_quantity_cart
  patch 'cart/decrement_quantity/:id', to: 'cart#decrement_quantity', as: :decrement_quantity_cart

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :plants, through: :orderables
  has_one :order

  def subtotal
    orderables.to_a.sum {|orderable| orderable.total_plant}
  end

  def shipping
    10
  end

  def total
    value_1 = subtotal
    value_2 = shipping
    return value_1 + value_2
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cart
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :cart
  belongs_to :plant

  def total_plant
    plant.price * quantity
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :orderables
  has_many :carts, through: :orderables

  include PgSearch::Model
  pg_search_scope :search_by,
  against: [:name],
  using: {
    tsearch: { prefix: true }
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_render_cart
  before_action :initialize_cart

  def set_render_cart
    @render_cart = true
  end

  def initialize_cart
    @cart = Cart.find_by(id: session[:cart_id])

    if @cart.nil?
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include ActionView::RecordIdentifier

  def show
    @render_cart = false
  end

  def add
    @plant = Plant.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(plant_id: @plant.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity + 1)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(plant: @plant, quantity: quantity)
    end
    redirect_to root_path, notice: "The plant was added to your cart"
  end

  def remove
    Rails.logger.debug "Params received in remove: #{params.inspect}"

    orderable = Orderable.find_by(id: params[:id])

    if orderable
      orderable.destroy
      Rails.logger.debug "Orderable destroyed: #{orderable.inspect}"

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('cart', partial: 'cart/cart', locals: { cart: @cart })
        end
        format.html { redirect_to cart_path, notice: "Item removed successfully." }
      end
    else
      Rails.logger.debug "Orderable not found with id: #{params[:id]}"

      respond_to do |format|
        format.html { redirect_to cart_path, alert: "Item not found." }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('cart', partial: 'cart/cart', locals: { cart: @cart })
        end
      end
    end
  end

  def increment_quantity
    orderable = Orderable.find_by(id: params[:id], cart_id: @cart.id)

    if orderable
      orderable.increment!(:quantity)
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace(dom_id(orderable), partial: 'cart/orderable', locals: { orderable: orderable }) }
        format.html { redirect_to cart_path, notice: "Quantity increased." }
      end
    else
      respond_to do |format|
        format.html { redirect_to cart_path, alert: "Item not found." }
      end
    end
  end

  def decrement_quantity
    orderable = Orderable.find_by(id: params[:id], cart_id: @cart.id)

    if orderable && orderable.quantity > 1
      orderable.decrement!(:quantity)
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace(dom_id(orderable), partial: 'cart/orderable', locals: { orderable: orderable }) }
        format.html { redirect_to cart_path, notice: "Quantity decreased." }
      end
    else
      respond_to do |format|
        format.html { redirect_to cart_path, alert: "Cannot decrease quantity below 1." }
      end
    end
  end

  def order
    @cart.id
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index

  end

  def new
    @order = Order.new
    @orderable = Orderable.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def index
    if params[:query].present?
      @plants = Plant.search_by(params[:query]) # Use the `pg_search_scope`
    else
      @plants = Plant.all
    end
    
  end


  def show
    @plant = Plant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do  %>
  <% if @cart.orderables.count > 0 %>
    <%= render "cart/orderables" %>
  <% else %>
    <div class="alert alert-danger" role="alert">
        Your cart is empty
    </div>
  <% end %>
<% end %>

app/views/cart/_orderable.html.erb
<div id="<%= dom_id(orderable) %>" class="row cart-item mb-3">
  <div class="card-cart mb-4">
    <div class="card-body-cart">
      <div class="row align-items-center" data-controller="quantity">
        <!-- Image Column -->
        <div class="col-12 col-md-3 text-center mb-3 mb-md-0">
          <img src="<%= orderable.plant.image %>" class="img-fluid img-cart rounded" alt="<%= orderable.plant.name %>">
        </div>

        <!-- Plant Details Column -->
        <div class="col-12 col-md-5 text-center text-md-start mb-3 mb-md-0">
          <h5 class="card-title"><%= orderable.plant.name %></h5>
          <p class="mb-1">Unit price:</p>
          <p data-quantity-target="price"><%= orderable.plant.price %></p>
        </div>

        <!-- Quantity Controls Column -->
        <div class="col-12 col-md-2 text-center mb-3 mb-md-0">
          <div class="input-group justify-content-center">
            <%= button_to "-", decrement_quantity_cart_path(orderable.id), method: :patch, remote: true, class: "btn btn-outline-secondary btn-sm", disabled: (orderable.quantity <= 1), data: { action: "quantity#decrement" } %>
            <input type="text" class="form-control form-control-sm text-center quantity-input" value="<%= orderable.quantity %>" data-quantity-target="quantity" data-action="input->quantity#changeTotal">
            <%= button_to "+", increment_quantity_cart_path(orderable.id), method: :patch, remote: true, class: "btn btn-outline-secondary btn-sm", data: { action: "quantity#increment" } %>
          </div>
        </div>

        <!-- Price and Delete Column -->
        <div class="col-12 col-md-2 text-center text-md-end">
          <h6 class="fw-bold">Price:</h6>
          <span data-quantity-target="calculation"><%= orderable.plant.price * orderable.quantity %></span>
          <form class="button_to mt-2" method="post" action="/cart/remove.turbo_stream">
            <input type="hidden" name="_method" value="delete" autocomplete="off" />
            <input type="hidden" name="id" value="<%= orderable.id %>" />
            <button data-confirm="Are you sure you want to delete this item?" class="btn btn-outline-danger btn-sm" type="submit">
              <i class="fa-solid fa-trash"></i>
            </button>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" autocomplete="off" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cart/_orderables.html.erb
<div class="container py-5" data-controller="subtotal">
    <h1 class="mb-5" style="justify-self:center">Your Shopping Cart</h1>
    <div class="row">
        <div class="col-lg-8">
          <% @cart.orderables.each do |orderable| %>
            <%= render partial: 'cart/orderable', locals: { orderable: orderable }, data: {target: "orberable"} %>
          <% end %>
            <!-- Continue Shopping Button -->
            <div class="text-start mb-4">
              <%= link_to "Continue Shopping", root_path, data: { turbo: false }, class: "btn btn-primary btn-prim" %>
            </div>
        </div>
        <div class="col-lg-4">
            <!-- Cart Summary -->
            <div class="card-cart cart-summary">
                <div class="card-body">
                    <h5 class="card-title mb-4">Order Summary</h5>
                    <div class="d-flex justify-content-between mb-3">
                        <span>Subtotal</span>
                        <span data-subtotal-target="subtotal"> <%= @cart.subtotal %> €</span>
                    </div>
                    <div class="d-flex justify-content-between mb-3">
                        <span>Shipping</span>
                        <span data-subtotal-target="shipping"><%= @cart.shipping %> €</span>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between mb-4">
                        <strong>Total</strong>
                        <strong data-subtotal-target="final"><%= @cart.total %>€</strong>
                    </div>
                    <%= link_to "Proceed to checkout", new_cart_order_path, class: "btn btn-primary btn-prim w-100", data: { turbo: false }  %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/cart/order.html.erb
<h1>hello</h1>
<%= @cart.id %>

app/views/cart/show.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= key == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plantsfun</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
<%= render "shared/navbar" %>
  <body>
    <div id="flash">
    <%= render 'layouts/flash' %>
  </div>
    <%= yield %>
  </body>
  <%= render "shared/footer" %>
</html>

app/views/orders/_order.html.erb
<div id="<%= dom_id(orderable) %>" class="mb-3">
  <div class=" d-flex justify-content-between gap-3">
    <h5 class="text-start"><%= orderable.plant.name %></h5>
    <div class="text-end">
      <p class="mb-0"><%= orderable.plant.price * orderable.quantity %></p>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<div class="container py-5">
  <h1 class="mb-4 text-center">Your Shipping Information</h1>
  <div class="row">
    <div class="col-lg-8">
      <div class="card shadow-sm">
        <div class="card-body">
          <%= form_with model: @order, url: "/cart/orders/new", local: true do |f| %>
            <div class="row">
              <div class="col-md-6 mb-3">
                <%= f.label :name, class: "form-label" %>
                <%= f.text_field :name, required: true, class: "form-control" %>
              </div>
              <div class="col-md-6 mb-3">
                <%= f.label :last_name, class: "form-label" %>
                <%= f.text_field :last_name, required: true, class: "form-control" %>
              </div>
            </div>
            <div class="mb-3">
              <%= f.label :email, class: "form-label" %>
              <%= f.email_field :email, required: true, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= f.label :address, class: "form-label" %>
              <%= f.text_field :address, required: true, class: "form-control" %>
            </div>
            <div class="row">
              <div class="col-md-6 mb-3">
                <%= f.label :city, class: "form-label" %>
                <%= f.text_field :city, required: true, class: "form-control" %>
              </div>
              <div class="col-md-2 mb-3">
                <%= f.label :zipcode, class: "form-label" %>
                <%= f.text_field :zipcode, required: true, class: "form-control" %>
              </div>
            </div>
            <div class="d-grid">
              <%= f.submit "Place Order", class: "btn btn-primary btn-lg btn-prim" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title mb-4 text-center">Order Summary</h5>
          <div class="d-flex flex-column gap-3">
            <% @cart.orderables.each do |orderable| %>
              <%= render partial: 'orders/order', locals: { orderable: orderable }, data: {target: "orderable"} %>
            <% end %>
          </div>
            <h6><strong>Shipping: </strong><%= @cart.shipping %>€</h6>
            <h6><strong>Total: </strong><%= @cart.total %>€</h6>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/cart.html.erb
<%= render partial: "cart/cart" if @render_cart %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/plants/index.html.erb
<%# Banner %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1470058869958-2a77ade41c02?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1>Plants for <strong>everyone</strong>!</h1>
    <p>Happy and green spaces for all</p>
  </div>
</div>
<%# Search bar %>
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: root_path, method: :get, class: "d-flex mt-4" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search by plant name"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary btn-prim" %>
    <% end %>
  </div>
</div>

<%# plants container %>
<div class="container">
  <% if @plants.any? %>
    <div class="row">
      <% @plants.each do |plant| %>
        <div class="col-12 col-sm-6 col-lg-3 d-flex justify-content-center mb-4">
          <div class="card" style="width: 20rem;">
            <img src="<%= plant.image %>" class="card-img-top rounded mx-auto d-block" alt="<%= plant.name %>">
            <div class="card-body">
              <h5 class="card-title"><%= plant.name %></h5>
              <h6 class="card-subtitle mb-3 text-body-secondary"><%= plant.category %></h6>
              <p class="card-text">Level: <%= plant.level %>, price: <%= plant.price %>€</p>
              <div class="d-flex justify-content-center gap-3">
                <button type="button" class="btn btn-primary btn-prim" data-bs-toggle="modal" data-bs-target="#plantModal<%= plant.id %>">
                  Details
                </button>
                <%= form_with(url: cart_add_path) do |f| %>
                  <%= f.hidden_field :id, value: plant.id %>
                  <%= f.hidden_field :quantity, value: 1, min: 1 %>
                  <%= f.submit "Add to cart", class: "btn btn-primary btn-prim" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <!-- Modale unique pour chaque plante -->
        <div class="modal fade bd-example-modal-lg" id="plantModal<%= plant.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel<%= plant.id %>" aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-body d-flex flex-column align-items-center bubble">
                <!-- Contenu spécifique à chaque plante -->
                <img src="<%= plant.image %>" alt="<%= plant.name %>" class="img-fluid modal-img mb-3">
                <p><strong>Category:</strong> <%= plant.category %></p>
                <p><strong>Level:</strong> <%= plant.level %></p>
                <p><strong>Price:</strong> <%= plant.price %>€</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary btn-prim">Save changes</button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>No plants found matching your query.</p>
  <% end %>
</div>

app/views/plants/show.html.erb
<h2><%= @plant.name %></h2>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light bg-light navbar-lewagon">
  <div class="container-fluid">
    <!-- Brand Logo -->
    <%= link_to "/", class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "https://img.freepik.com/premium-vector/cartoon-seaweed-green-underwater-plant-stones-rocks-sea-bottom-decoration-vector-undersea-plant-grown-aquarium-tank-decor-tropical-seabed-marine-life-object-undersea-aquatic-flora_53500-892.jpg?w=1060", size: "40x40", class: "me-2 rounded-circle" %>
      Plants for everyone
    <% end %>

    <!-- Navbar Toggler -->
    <%= link_to cart_path, class: "nav-link" do %>
            <i class="fa-solid fa-cart-shopping"></i>
          <% end %>
    <!-- Collapsible Menu -->
  </div>
</div>